# Generated by Django 4.1.7 on 2023-04-14 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 14, 22, 56, 52, 393230, tzinfo=datetime.timezone.utc)),
        ),
    ]
