# Generated by Django 4.1.7 on 2023-06-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='previous_times',
            field=models.FloatField(default=0),
        ),
    ]
